<template>
  <div class="chat-container">
    <div class="messages-container" ref="messagesContainer">
      <div v-if="messages.length === 0" class="welcome-message">
        <div class="welcome-card">
          <h2>👋 Hello!</h2>
          <p>I'm your AI assistant. Ask me anything!</p>
          <div class="example-queries">
            <p><strong>Try asking:</strong></p>
            <p>"What is the company policy on vacation?"</p>
            <p>"Tell me about remote work"</p>
          </div>
        </div>
      </div>
      
      <MessageBubble
        v-for="message in messages"
        :key="message.id"
        :message="message"
      />
      
      <LoadingIndicator v-if="isLoading" />
    </div>
    
    <InputArea
      @send-message="handleSendMessage"
      :disabled="isLoading"
    />
  </div>
</template>

<script setup lang="ts">
// ==============================================================================
// CHAT CONTAINER COMPONENT (STATE ORCHESTRATOR)
// ==============================================================================
// This is the core state management component of the user interface.
// It manages:
// 1. The list of chat messages (both user questions and AI responses)
// 2. Loading state indicators
// 3. Invoking the streaming API and updating the DOM in real-time as tokens arrive
// 4. Automatic scrolling to keep new content visible

import { ref, nextTick, onMounted } from 'vue'

// Import child UI components:
// - MessageBubble: Renders individual message text bubbles (blue for user, grey for AI)
// - InputArea: Text box and send button
// - LoadingIndicator: 3-dot animated bouncing indicator ("AI is thinking...")
import MessageBubble from './MessageBubble.vue'
import InputArea from './InputArea.vue'
import LoadingIndicator from './LoadingIndicator.vue'

// Import API communication functions
import { searchPolicyStream, searchPolicySimple } from '../services/apiService'

// ------------------------------------------------------------------------------
// TypeScript Interface: Message Structure
// ------------------------------------------------------------------------------
interface Message {
  id: number         // Unique numeric ID for Vue's :key tracking
  text: string       // Message content (markdown or plain text)
  isUser: boolean    // true if sent by the human user; false if generated by AI
  timestamp: Date    // Creation timestamp for displaying time (e.g. 10:45 AM)
}

// ------------------------------------------------------------------------------
// Reactive State Variables (Vue 3 ref)
// ------------------------------------------------------------------------------
// ref() creates a reactive wrapper around a value. Whenever .value changes,
// Vue automatically detects it and re-renders only the parts of the DOM that depend on it.
const messages = ref<Message[]>([])
const isLoading = ref(false)
const messagesContainer = ref<HTMLElement>() // Ref bound to the scrollable HTML div in template
let messageIdCounter = 0

// ------------------------------------------------------------------------------
// Helper: Auto-Scroll to Bottom of Chat
// ------------------------------------------------------------------------------
const scrollToBottom = () => {
  // nextTick() defers execution until Vue has finished updating the virtual DOM.
  // This guarantees that we calculate scrollHeight AFTER the new message has been drawn.
  nextTick(() => {
    if (messagesContainer.value) {
      messagesContainer.value.scrollTop = messagesContainer.value.scrollHeight
    }
  })
}

// ------------------------------------------------------------------------------
// Main Action: Send Message & Stream AI Response
// ------------------------------------------------------------------------------
const handleSendMessage = async (messageText: string) => {
  // Ignore empty or whitespace-only messages
  if (!messageText.trim()) return
  
  // 1. Create and append the user's question bubble
  const userMessage: Message = {
    id: messageIdCounter++,
    text: messageText,
    isUser: true,
    timestamp: new Date()
  }
  messages.value.push(userMessage)
  scrollToBottom()
  
  // 2. Activate the loading indicator while waiting for the first token
  isLoading.value = true
  
  try {
    let hasReceivedData = false
    
    try {
      // 3. Attempt real-time token streaming from FastAPI
      await searchPolicyStream(messageText, (chunk: string) => {
        console.log('Processing chunk in UI:', chunk)
        
        if (!hasReceivedData) {
          // FIRST TOKEN RECEIVED:
          // Create the AI's response bubble in the chat list with this first chunk.
          const aiMessage: Message = {
            id: messageIdCounter++,
            text: chunk,
            isUser: false,
            timestamp: new Date()
          }
          messages.value.push(aiMessage)
          hasReceivedData = true
          console.log('Created new AI message with first chunk:', aiMessage.text)
        } else {
          // SUBSEQUENT TOKENS RECEIVED:
          // Find the last message (which is our active AI message) and append the new chunk.
          const lastMessageIndex = messages.value.length - 1
          const lastMessage = messages.value[lastMessageIndex]
          
          if (lastMessage && !lastMessage.isUser) {
            // In Vue 3, mutating nested object properties directly can sometimes miss reactivity.
            // Creating a new object and replacing it via .splice() reliably triggers Vue reactivity!
            const updatedMessage: Message = {
              ...lastMessage,
              text: lastMessage.text + chunk
            }
            messages.value.splice(lastMessageIndex, 1, updatedMessage)
            console.log('Updated AI message, new text length:', updatedMessage.text.length)
          }
        }
        
        // Keep view pinned to bottom as text expands
        nextTick(() => {
          scrollToBottom()
        })
      })
    } catch (streamError) {
      // 4. STREAMING FALLBACK:
      // If streaming fails (e.g. network proxy or browser issue), attempt simple HTTP request
      console.log('Streaming failed, trying simple request:', streamError)
      
      try {
        const response = await searchPolicySimple(messageText)
        if (response && response.trim()) {
          const fallbackMessage: Message = {
            id: messageIdCounter++,
            text: response,
            isUser: false,
            timestamp: new Date()
          }
          messages.value.push(fallbackMessage)
          hasReceivedData = true
        }
      } catch (fallbackError) {
        console.error('Both streaming and simple request failed:', fallbackError)
      }
    }
    
    // 5. HELPFUL EMPTY-STATE MESSAGE:
    // If no data arrived (e.g., no documents in vector store), provide guidance
    if (!hasReceivedData) {
      const helpMessage: Message = {
        id: messageIdCounter++,
        text: "I'm sorry, I couldn't find relevant information about that topic. This might be because:\n\n• No policy documents have been uploaded yet\n• The backend AI model isn't loaded\n• Your query doesn't match the available documents\n\nTry uploading some PDF documents first using the /policy/upload endpoint.",
        isUser: false,
        timestamp: new Date()
      }
      messages.value.push(helpMessage)
    }
    
  } catch (error) {
    // 6. SERVER CONNECTION ERROR:
    console.error('Error getting AI response:', error)
    
    const errorMessage: Message = {
      id: messageIdCounter++,
      text: 'Sorry, I encountered an error while processing your request. Please make sure the backend server is running on http://localhost:8000.',
      isUser: false,
      timestamp: new Date()
    }
    messages.value.push(errorMessage)
  } finally {
    // 7. CLEANUP: Always deactivate loading indicator and ensure view is scrolled down
    isLoading.value = false
    scrollToBottom()
  }
}

// Auto-scroll when the component first mounts to the DOM
onMounted(() => {
  scrollToBottom()
})
</script>

<style scoped>
.chat-container {
  flex: 1;
  display: flex;
  flex-direction: column;
  max-width: 800px;
  margin: 0 auto;
  height: calc(100vh - 100px);
}

.messages-container {
  flex: 1;
  overflow-y: auto;
  padding: 0.75rem;
  margin-bottom: 0.5rem;
}

.welcome-message {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100%;
  min-height: 200px;
}

.welcome-card {
  background: #2d3748;
  border-radius: 12px;
  padding: 1.5rem;
  text-align: center;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3);
  border: 1px solid #4a5568;
  max-width: 400px;
}

.welcome-card h2 {
  color: #e2e8f0;
  margin: 0 0 0.75rem 0;
  font-size: 1.3rem;
}

.welcome-card p {
  color: #a0aec0;
  margin: 0 0 1rem 0;
  font-size: 0.95rem;
}

.example-queries {
  text-align: left;
  background: #1a202c;
  border-radius: 8px;
  padding: 0.75rem;
  margin-top: 0.75rem;
}

.example-queries p {
  margin: 0.3rem 0;
  color: #cbd5e0;
  font-size: 0.85rem;
}

.example-queries p:first-child {
  font-weight: 600;
  margin-bottom: 0.5rem;
  color: #e2e8f0;
}

/* Scrollbar styling */
.messages-container::-webkit-scrollbar {
  width: 6px;
}

.messages-container::-webkit-scrollbar-track {
  background: #2d3748;
  border-radius: 3px;
}

.messages-container::-webkit-scrollbar-thumb {
  background: #4a5568;
  border-radius: 3px;
}

.messages-container::-webkit-scrollbar-thumb:hover {
  background: #718096;
}
</style>